# Generated by Django 4.1.5 on 2023-04-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
